language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
before_script:
- npm install -g gulp
script: gulp travis
before_install:
- openssl aes-256-cbc -K $encrypted_86801d563202_key -iv $encrypted_86801d563202_iv
  -in travis.tar.enc -out travis.tar -d
- tar xvf travis.tar
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - gcc-4.9
      - libc6-dev

before_install:
  - export CC=/usr/bin/gcc-4.9;
  - export CXX=/usr/bin/g++-4.9;
